name: System Release Building
  
on:
  release:
    types: [published]

jobs:
  packAndBuild:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3      
      
      - name: Setup Node and Foundry CLI
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g @foundryvtt/foundryvtt-cli
      - run: fvtt configure set "dataPath" ${GITHUB_WORKSPACE}
      - run: fvtt package workon "opsandtactics" --type "System"
      
      - name: Create Packs from Source
      - run: fvtt package pack "aa-armors" --in "src/packs/aa-armors" --out "packs"
      - run: fvtt package pack "aa-melee-weapons" --in "src/packs/aa-melee-weapons" --out "packs"
      - run: fvtt package pack "aa-races" --in "src/packs/aa-races" --out "packs"
      - run: fvtt package pack "core-archaic-weapons" --in "src/packs/core-archaic-weapons" --out "packs"
      - run: fvtt package pack "core-armors" --in "src/packs/core-armors" --out "packs"
      - run: fvtt package pack "core-feats" --in "src/packs/core-feats" --out "packs"
      - run: fvtt package pack "core-firearms" --in "src/packs/core-firearms" --out "packs"
      - run: fvtt package pack "core-melee-weapons" --in "src/packs/core-melee-weapons" --out "packs"
      - run: fvtt package pack "core-ranged-weapons" --in "src/packs/core-ranged-weapons" --out "packs"
      - run: fvtt package pack "mm-armors" --in "src/packs/mm-armors" --out "packs"
      - run: fvtt package pack "mm-melee-weapons" --in "src/packs/mm-melee-weapons" --out "packs"
      - run: fvtt package pack "mm-races" --in "src/packs/mm-races" --out "packs"
      - run: fvtt package pack "system-reference" --in "src/packs/system-reference" --out "packs"
      - run: fvtt package pack "weapon-templates" --in "src/packs/weapon-templates" --out "packs"

      - name: Zip Creation
        run: |
          zip                   \
          --recurse-paths       \
          ./opsandtactics.zip   \
          LICENSE.txt           \
          README.md             \
          system.json           \
          template.json         \
          css/                  \
          icons/                \
          lang/                 \
          lib/                  \
          module/               \
          packs/                \
          templates/            \
      
      - name: Add Artifacts to Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.unpublished }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './system.json, ./opsandtactics.zip'
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
