name: System Release Building
  
on:
  release:
    types: [published]

jobs:
  packAndBuild:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4      
      
      - name: Setup Node and Foundry CLI
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install -g @foundryvtt/foundryvtt-cli
      - run: fvtt configure set "dataPath" ${GITHUB_WORKSPACE}
      - run: fvtt package workon "opsandtactics" --type "System"
      
      - run: fvtt package pack "system-reference" --in "src/packs/system-reference" --out "packs"
      - run: fvtt package pack "core-rulebook" --in "src/packs/core-rulebook" --out "packs"
      - run: fvtt package pack "mm-rulebook" --in "src/packs/mm-rulebook" --out "packs"
      - run: fvtt package pack "aa-rulebook" --in "src/packs/aa-rulebook" --out "packs"
      - run: fvtt package pack "procedural" --in "src/packs/procedural" --out "packs"


      - name: Zip Creation
        run: |
          zip                   \
          --recurse-paths       \
          ./opsandtactics.zip   \
          LICENSE.txt           \
          README.md             \
          system.json           \
          template.json         \
          css/                  \
          icons/                \
          lang/                 \
          lib/                  \
          module/               \
          packs/                \
          templates/            \
      
      - name: Add Artifacts to Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.unpublished }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './system.json, ./opsandtactics.zip'
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
